Adding base for new UserManagementAPI module
tiagosiebler/microstrategy-api-node pull request #4
Opened 2020-03-31 23:31 UTC by danielzumb

(Also small update to README.md)

2020-04-01 08:42 UTC, tiagosiebler requested changes
Looking great!

2020-04-01 08:42 UTC, tiagosiebler commented on lib/restAPIs/userManagement.js
> +    getUsers(nameBegins = '', abbreviationBegins = '', offset = 0, limit = -1){
As discussed - optional parameters should be left blank and omitted from the request if empty:
```
getUsers(nameBegins, abbreviationBegins, offset = 0, limit = -1){
  const queryParameter = {
        offset: offset,
        limit: limit
  }
  
  if (nameBegins) {
    queryParameter.nameBegins = nameBegins;
  }
  
  if (abbreviationBegins) {
    queryParameter.abbreviationBegins = abbreviationBegins;
  }

  return this._makeRequest(this._getBase(), queryParameter, 'GET')
  .then(result => this.throwIfFailed(result, 200));
}
```

2020-04-01 08:42 UTC, tiagosiebler commented on lib/restAPIs/userManagement.js
> +    getUsers(nameBegins = '', abbreviationBegins = '', offset = 0, limit = -1){
Missing the "fields" param - I would add it as last in the list

2020-04-01 08:42 UTC, tiagosiebler commented on lib/restAPIs/userManagement.js
> +    getUsers(nameBegins = '', abbreviationBegins = '', offset = 0, limit = -1){
Lastly, please use indentation of 2 spaces

2020-04-08 15:32 UTC, danielzumb reviewed
Self reviewed

2020-04-08 15:48 UTC, tiagosiebler approved these changes
Looks great!

2020-04-08 15:48 UTC, merged